### ISSUE TITLE
Add your fork to the extensions-catalog

### ISSUE THREAD

**Issue by Sean-Der** [websupport-sk/pecl-memcache#1]
Hi!

Really nice work with this port, would you mind updating the [extensions catalog](https://github.com/gophp7/gophp7-ext/wiki/extensions-catalog) to include your port?

thanks

**Comment by szabolcsbalogh** [comment]
maybe it will be merged into php.net version,
see
http://marc.info/?l=pecl-dev&m=144734279830573&w=2

**Comment by Sean-Der** [comment]
That is awesome to hear @szabolcsbalogh !

Adding your fork right now would be helpful for people who want to use your work right now. I just stumbled upon this repo because I was linked by someone else. Totally your choice though.

thanks for working on this

**Comment by pierrejoye** [comment]
My bad. I will merge it between now and next week.it 

Sorry, it badly went off my radar :/
