### ISSUE TITLE
Any official word on future plans for Memcache? PHP 7?

### ISSUE THREAD

**Issue by RoxKilly** [websupport-sk/pecl-memcache#11]
The `README` here is a few years old now, and some of the functions it describes are still not implemented as documented (in the Windows DLL of 3.0.8 at least).  

`3.0.8` has been in beta for 3 years I think. Now that we're making plans to move to PHP 7, we'd like some clarity please on whether this project should be considered dormant.

We're trying to decide whether to make plans to switch from this extension to `Memcached`, since that extension is actively working to be PHP 7 compatible. Any guidance would be welcome. We really don't want to switch unless we have to.

Using `PHP 5.6.23` with `Memcache 3.0.8` on Windows 7 (development) and CentOS 7 (production)

**Comment by inliquid** [comment]
Up

**Comment by Jan-E** [comment]
@RoxKilly Try the php_memcache.dll in my PHP 7.0.9 RC1 builds. It is built using the latest sources of this repo. Download thru

https://www.apachelounge.com/viewtopic.php?t=6617

phpinfo() dump:
https://phpdev.toolsforresearch.com/php-7.0.9RC1-Win32-VC14-x64.htm

The php_memcache.dll in the PHP 5.6.24 RC1 build still is v3.0.8, but I could build that one from the newest sources as well.

**Comment by RoxKilly** [comment]
@Jan-E I'm completely unfamiliar with building from source. The DLL would be a drop-in replacement for my current `memcache` `.dll` file on Windows once I switch to PHP 7 right? That'll take care of my development machine (Windows) if I'm correct.  

The production machine is a Linux CentOS 7 server, and the extension it uses is version 3.0.8 installed from http://pecl.php.net/package/memcache .  Any idea how to update that?

**Comment by arvenil** [comment]
Any update on this?

**Comment by electropolis** [comment]
Are you asking about memcache or memcached ?

**Comment by RoxKilly** [comment]
About [this project](http://pecl.php.net/package/memcache): the PHP `memcache` extension

**Comment by archon810** [comment]
Would also love to know the status of php pecl memcache extension for PHP 7.1.

**Comment by Jan-E** [comment]
Somebody reported a problem with this repo and PHP 7.1:
https://www.apachelounge.com/viewtopic.php?p=34623#34623

**Comment by tomassrnka** [comment]
I've tried to get in touch with official repo maintainer - no luck. I will update README on this page. Feel free to use it / post patches / fork it.

We will dedicate on of our dev. people for last 7-10days of this month to update memcache extension for PHP 7.1.X.
