### ISSUE TITLE
Need explanations regarding RPM packaging errors

### ISSUE THREAD

**Issue by aursu** [websupport-sk/pecl-memcache#12]
Hi!

I'm trying to create RPM package for PHP7 on CentOS7. I have 2 question:
1) In commit 1a28da3ff6776fe9732dce06328d10208150fc1b you've made next change:

`diff -rup -x .git pecl-memcache.php5.orig/memcache.c pecl-memcache.php5/memcache.c`
`--- pecl-memcache.php5.orig/memcache.c 2016-07-29 03:06:28.657638787 +0200`
`+++ pecl-memcache.php5/memcache.c  2016-07-29 02:57:22.434994396 +0200`
`@@ -1658,7 +1658,7 @@ PHP_FUNCTION(memcache_get)`

`/* allocate request */`
`request = mmc_pool_request_get(`
`-          pool, MMC_PROTO_UDP,`
`+          pool, MMC_PROTO_TCP,`
`mmc_value_handler_single, value_handler_param,`
`mmc_pool_failover_handler, NULL);`

Could you explain why do you done this? This caused 038.phpt test fail  with next result:

/usr/bin/php7 --no-php-ini --define extension=/root/rpmbuild/BUILDROOT/php7-pecl-memcache-3.0.8-1.el7.centos.x86_64/usr/lib64/php7/modules/memcache.so  /root/rpmbuild/BUILD/php7-pecl-memcache-3.0.8/NTS/tests/038.php
bool(true)
bool(true)
array(2) {
  ["test_key1"]=>
  string(3) "abc"
  ["test_key2"]=>
  string(3) "def"
}
array(1) {
  ["test_key1"]=>
  string(3) "abc"
}

Notice: MemcachePool::get(): Server localhost (tcp 11213, udp 11211) failed with: Connection refused (111) in /root/rpmbuild/BUILD/php7-pecl-memcache-3.0.8/NTS/tests/038.php on line 20
bool(false)

It tries to connect to non-existing TCP port 11213 instead of UDP 11211. I'm expect that you've made an error in mentioned commit

2) In commit f9d3342e7c1daf34515844869f892cc83fa913f9 you've added to file memcache_binary_protocol.c next line: 

header = (mmc_store_request_header_t *)(request->sendbuf.value.c + prevlen);

Variable header (its pointer) is declared using type "mmc_store_append_header_t" but in this commit you use type cast to "mmc_store_request_header_t"

This causes compiler warning. Is it correct casting in this particular case or could be changed to declaration type "mmc_store_append_header_t"

Thanks

**Comment by tomassrnka** [comment]
Hi, could you please try it again? There has been a major release since 2016
