### ISSUE TITLE
session_regenerate_id() causes fatal error

### ISSUE THREAD

**Issue by gman-wa** [websupport-sk/pecl-memcache#13]
using this memcache extension as the session save handler, session_regenerate_id() returns a fatal error.

This is related to https://bugs.php.net/bug.php?id=71187

In a comment by yohgaki@php.net he offers the reason for the error and a potential fix for the memcached client that perhaps you could use to implement a fix in this memcache client?

**Comment by gsmaul** [comment]
I added a patch for this in my fork, based on the feedback in the PHP bug you've linked. I'm still in the process of testing the patch - haven't pushed it onto loaded production servers yet, but seems stable in my dev environment.

https://github.com/gsmaul/pecl-memcache/commit/9a3471d975e9852d444358878a4004d03229b4ad

Any feedback is welcomed, as I don't regularly work on PHP extensions.

**Comment by tomassrnka** [comment]
This seems to work pretty fine, can someone else please confirm the patch?

**Comment by kmille** [comment]
@gsmaul Can you please merge it. We need fix.

**Comment by gsmaul** [comment]
Submitted a pull request from my repo. I'm no longer using/testing this lib, so I'll pass it along to someone else for maintenance. I did test this patch for a short while back in 2016 and didn't run into any issues.

**Comment by tomassrnka** [comment]
Thanks, the patch has been included in the source code for some time. I believe the bug no longer occurs.

**Comment by victorhahncastell** [comment]
PR #50 (just linking this for convenience)

Thanks for patching this! :-)
