### ISSUE TITLE
Causes PHP 7.0.14 Crash 

### ISSUE THREAD

**Issue by jjeau75** [websupport-sk/pecl-memcache#19]
Hi guys.

Appears this port does not work when installed on PHP 7.0.14 - the current FreeBSD distro. It actually causes a complete PHP crash on every execution.

Any help appreciated.

Thanks.

**Comment by mk-j** [comment]
Is it a fatal error - out of memory error?
see https://bugs.php.net/bug.php?id=73539
and https://bugs.php.net/bug.php?id=73497

**Comment by tomassrnka** [comment]
There are some new patches for memory leaks, give it a try pls, I do not have FreeBSD near me at the moment. To be honest, we've never tried it on FBSD. Let me know, Thanks,Tomas

**Comment by tomassrnka** [comment]
Unfortunately, PHP 7.0 is no longer supported. ver. 4.0.2 works fine with 7.3 (passing all tests), 7.2 works with failing tests.
