### ISSUE TITLE
MemcachePool not found

### ISSUE THREAD

**Issue by digitalkaoz** [websupport-sk/pecl-memcache#2]
hey, thanks for porting :)

if i use this extension (i checked in phpinfo, and yes its loaded) i get: `ClassNotFoundException:
Attempted to load class "MemcachePool" from the global namespace.
Did you forget a "use" statement?` i guess, the object oriented layer is missing in the pecl extension?

my php env:

```
$ php --version
PHP 7.0.0RC6 (cli) (built: Oct 29 2015 13:46:05) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

but if i use the attached `memcache.php` it seems to work :/

**Comment by szabolcsbalogh** [comment]
i ported master branch, which seems to be a continue of release 2.2.7...
tag with 3.0.8 is a commit with full source, last branched commit is 3.0.6, so i need to solve, from which point to port it again

**Comment by digitalkaoz** [comment]
i guess use `3.0.8` ?! and yes afaik the class was introduced in the 3.x Branch...

**Comment by digitalkaoz** [comment]
@szabolcsbalogh are you willing to re-port the 3.x branch?

**Comment by szabolcsbalogh** [comment]
yes, i started to work on it.

**Comment by digitalkaoz** [comment]
:-*

**Comment by szabolcsbalogh** [comment]
take a look at branch NON_BLOCKING_IO_php7

the original php5 version is buggy, but i tried my best, and i have less failing tests on php7 version than on php5. UDP protocol have problems, and can end up in an infinity loop, so try to not use it for now.

**Comment by digitalkaoz** [comment]
works like a charm :-*
