### ISSUE TITLE
Memcache extension can't read from memcached

### ISSUE THREAD

**Issue by nicolacontu** [websupport-sk/pecl-memcache#23]
Hello 
I've installed php 7.1.1 and the extensions is version 3.0.9-dev

When I try to do a session_start I get : 
Warning: session_start(): Failed to read session data: memcache (path: tcp://127.0.0.1:11211) in /usr/local/httpd-2.4.25/logs/test.php on line 1
array(0) {
}

This the script I used :
<?php session_start(); var_dump($_SESSION); $_SESSION['a'] = 'b'; ?> 

This is my php.ini
session.save_handler = memcache
session.save_path = '127.0.0.1:11211'
memcache.lock_timeout = 60
extension=memcache.so

Can you please check?
Thanks

**Comment by tomassrnka** [comment]
Hi, can you use memcache outside of the extension? We use the extension with PHP 7.1 without any problems.

**Comment by nicolacontu** [comment]
Hi,

yes I'm using it with php5.6.6 with the pecl-memcache extension 3.0.8


________________________________
Da: Tomas Srnka <notifications@github.com>
Inviato: mercoledì 19 aprile 2017 16.28
A: websupport-sk/pecl-memcache
Cc: nicolacontu; Author
Oggetto: Re: [websupport-sk/pecl-memcache] Memcache extension can't read from memcached (#23)


Hi, can you use memcache outside of the extension? We use the extension with PHP 7.1 without any problems.

**Comment by klandaika** [comment]
Having same issue here when using native session handler via php.ini directives and calling `session_start()` on PHP 7.1.4 :
```
session.save_handler = memcache
session.save_path = 'tcp://host:11211'
```

However when using `new Memcache()` with `addServer` all object functions work as expected and I am able to read/write data to the server.

On PHP 7.0.17 and same configs `session_start()` works correctly with native session handler

**Comment by krzaczek** [comment]
Same here 

`session_start(): Failed to read session data: memcache (path: tcp://127.0.0.1:11211)`

```
PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )
Version => 3.0.9-dev
```

`new Memcache()` is working fine. Only session support is broken. 

@tomassrnka

**Comment by ramsey** [comment]
I'm experiencing the same issue with PHP 7.1.7 and the latest commit of the memcache extension: e702b5f91ec222e20d1d5cea0ffc6be012992d70

Error message is the same:

```
session_start(): Failed to read session data: memcache (path: tcp://127.0.0.1:11211)
```

Has anyone found a work-around yet? I'm able to use the same extension on PHP 7.0.x without any problems.

**Comment by nicolacontu** [comment]
I just switched to memcahed extension


________________________________
Da: Ben Ramsey <notifications@github.com>
Inviato: giovedì 17 agosto 2017 01:14
A: websupport-sk/pecl-memcache
Cc: nicolacontu; Author
Oggetto: Re: [websupport-sk/pecl-memcache] Memcache extension can't read from memcached (#23)


I'm experiencing the same issue with PHP 7.1.7 and the latest commit of the memcache extension: e702b5f<https://github.com/websupport-sk/pecl-memcache/commit/e702b5f91ec222e20d1d5cea0ffc6be012992d70>

Error message is the same:

session_start(): Failed to read session data: memcache (path: tcp://127.0.0.1:11211)


Has anyone found a work-around yet? I'm able to use the same extension on PHP 7.0.x without any problems.

**Comment by ramsey** [comment]
I was able to create a simple reproducible version of this, using Docker. The repository is here: https://github.com/ramsey/pecl-memcache-issue-23

To run it to see the `session_start()` warning:

``` bash
git clone https://github.com/ramsey/pecl-memcache-issue-23
cd pecl-memcache-issue-23/
docker-compose up
```

Now, the two containers should be running, and you can open the following in your browser to verify:

* <http://localhost:8001/info.php> (should be running PHP 7.0)
* <http://localhost:8002/info.php> (should be running PHP 7.1)

To test the `session_start()` issue and see the warning, open the following:

* PHP 7.0: <http://localhost:8001/> (the session should work as expected)
* PHP 7.1: <http://localhost:8002/> (`session_start()` should generate a warning)

See [the repository](https://github.com/ramsey/pecl-memcache-issue-23) for more information.

I hope this helps! :smile:

**Comment by ramsey** [comment]
@tomassrnka, have you been able to take a look at my reproduction steps yet?

**Comment by Roze** [comment]
Since the php 7+ session module now expects a string for a valid response the error appears when the memcache extension returns that the key doesn't exist for a fresh/uninitialised session.

For me kind of works (haven't fully tested though (for example with binary protocol)) this small change:

```
--- pecl-memcache-NON_BLOCKING_IO_php7/php7/memcache_session.c  2017-08-02 12:38:18.000000000 +0300
+++ pecl-memcache-NON_BLOCKING_IO_php7/php7/memcache_session.c   2017-09-06 15:40:59.101003326 +0300
@@ -289,7 +289,7 @@
                        ZVAL_NULL(&addresult);

                        /* third request fetches the data, data is only valid if either of the lock requests succeeded */
-                       ZVAL_NULL(&dataresult);
+                       ZVAL_EMPTY_STRING(&dataresult);

                        /* create requests */
                        if (php_mmc_session_read_request(pool, &zkey, lockparam, &addresult, dataparam, &lockrequest, &addrequest, &datarequest) != MMC_OK) {

```

**Comment by krzaczek** [comment]
@Roze yep that fixes the problem ... thx

**Comment by remicollet** [comment]
@Roze could be better to open a pull request.

**Comment by nono303** [comment]
@remicollet Thanks for the patch!
Work fine on Windows.
dll build for 7.2.x VC15, x86 & X64 / TS & NTS available @ https://github.com/nono303/PHP7-memcache-dll

**Comment by JonathanFinch-awin** [comment]
I was getting the following error on PHP 7.2 with debian php-memcache 3.0.9:
```
Error #2 session_start(): Failed to read session data: memcache
```
I manually installed the latest php memcache version 4.0.4 in my dockerfile and this resolved the issue.
```
RUN apt-get install libz-dev \
&& cd /tmp \
&& wget -O "memcache-4.0.4.tar.gz" "https://github.com/websupport-sk/pecl-memcache/archive/4.0.4.tar.gz" \
&& tar -xvzf "memcache-4.0.4.tar.gz" \
&& cd "pecl-memcache-4.0.4" \
&& phpize \
&& ./configure \
&& make \
&& make install
```
