### ISSUE TITLE
Installation procedure?

### ISSUE THREAD

**Issue by sbernaldev** [websupport-sk/pecl-memcache#25]
Hello please could someone put to the readme how to install this in a php 7 FPM? I'm newbie :)

**Comment by baltazor5000** [comment]
First install php-dev package. 
For example Debian: 
 - apt-get install php7.0-dev.
 - git clone this repository
 - cd pecl-memcache
 - phpize
 - ./configure
 - make
 - make install

After:
cd /etc/php/7.0/mods-available
nano memcache.ini with: extension=memcache.so
cd /etc/php/7.0/fpm/conf.d/
ln -s /etc/php/mods-available/memcache.ini 20-memcache.ini
