### ISSUE TITLE
Update the memcache up to 3+ version (PHP7)

### ISSUE THREAD

**Issue by budby** [websupport-sk/pecl-memcache#27]
Could you update the memcache up to 3+ version?

**Comment by vitlav** [comment]
In other words, please, make a new release from php7 related branch.

**Comment by michaeljoseph** [comment]
The `NON_BLOCKING_IO_php7` branch is at `3.0.9-dev`

**Comment by tomassrnka** [comment]
There is a new release 4.0.0. that supports PHP up to 7.3
