### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by futureweb** [websupport-sk/pecl-memcache#28]
Hey there,
I wanted to ask about the current Status of PHP 7.2 compatibility as "make test" throws some Errors.

Centos 7
memcached Server Version: 1.4.15
PHP: 7.2.2

> Number of tests :   74                73
> Tests skipped   :    1 (  1.4%) --------
> Tests warned    :    0 (  0.0%) (  0.0%)
> Tests failed    :   22 ( 29.7%) ( 30.1%)
> Expected fail   :    0 (  0.0%) (  0.0%)
> Tests passed    :   51 ( 68.9%) ( 69.9%)

> make test | grep -i fail
> FAIL memcache->addServer() [tests/019.phpt] 
> FAIL memcache->set()/memcache->get() with multiple keys and load balancing [tests/020.phpt] 
> FAIL memcache->getExtendedStats() [tests/022.phpt] 
> FAIL memcache_get_extended_stats() [tests/022a.phpt] 
> FAIL memcache->delete() with load balancing [tests/023.phpt] 
> FAIL memcache->increment() with load balancing [tests/025.phpt] 
> FAIL memcache->delete() with load balancing [tests/026.phpt] 
> FAIL memcache->addServer() adding server in failed mode [tests/031.phpt] 
> FAIL memcache->getServerStatus(), memcache->setServerParams() [tests/032.phpt] 
> FAIL memcache::connect() with unix domain socket [tests/035.phpt] 
> FAIL ini_set('session.save_handler') [tests/036.phpt] 
> FAIL memcache->get() over UDP [tests/038.phpt] 
> FAIL memcache->get() over multi-datagram UDP [tests/039.phpt] 
> FAIL memcache->increment()/decrement() with multiple keys [tests/040.phpt] 
> FAIL memcache->delete() with multiple keys [tests/041.phpt] 
> FAIL memcache->set() with multiple values [tests/042.phpt] 
> FAIL ini_set('memcache.redundancy') [tests/043.phpt] 
> FAIL ini_set('memcache.session_redundancy') [tests/044.phpt] 
> FAIL hash strategies and functions [tests/046.phpt] 
> FAIL ini_set('session.save_handler') with unix domain socket [tests/053.phpt] 
> FAIL session locking [tests/057.phpt] 
> FAIL memcache multi host save path function [tests/bug73539.phpt] 

thx
Andreas Schnederle-Wagner

**Comment by artash** [comment]
I get less failures on CentOS 6.5, x86_64, PHP 7.2.3
```
=====================================================================
TIME END 2018-03-13 21:16:11

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   28
---------------------------------------------------------------------

Number of tests :   74                73
Tests skipped   :    1 (  1.4%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    8 ( 10.8%) ( 11.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   65 ( 87.8%) ( 89.0%)
---------------------------------------------------------------------
Time taken      :   36 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
memcache::connect() with unix domain socket [tests/035.phpt]
ini_set('session.save_handler') [tests/036.phpt]
memcache->get() over UDP [tests/038.phpt]
memcache->get() over multi-datagram UDP [tests/039.phpt]
ini_set('memcache.session_redundancy') [tests/044.phpt]
ini_set('session.save_handler') with unix domain socket [tests/053.phpt]
session locking [tests/057.phpt]
memcache multi host save path function [tests/bug73539.phpt]
=====================================================================
```

**Comment by tomassrnka** [comment]
At the moment, there are 3 tests failing for PHP 7.2, at least 2 of them are because of changed behaviour of sessions, otherwise it should work fine.

**Comment by tomassrnka** [comment]
Fixed in https://github.com/websupport-sk/pecl-memcache/pull/47
