### ISSUE TITLE
ZTS support

### ISSUE THREAD

**Issue by artash** [websupport-sk/pecl-memcache#29]
Looking at code I've noticed all TSRMLS_* macros were removed from php7 code. Doesn't this mean that it won't work when ZTS is enabled?

Was there a specific reason why TSRMLS_* macros were removed from code, e.g.
```
-static void _mmc_pool_list_dtor(zend_rsrc_list_entry * TSRMLS_DC);
+static void _mmc_pool_list_dtor(zend_resource *);
```
or
```
-		php_error_docref(NULL TSRMLS_CC, E_WARNING, "memcache.max_failover_attempts must be a positive integer ('%s' given)", new_value);
+		php_error_docref(NULL, E_WARNING, "memcache.max_failover_attempts must be a positive integer ('%s' given)", ZSTR_VAL(new_value));
```

**Comment by nikic** [comment]
PHP 7 no longer uses TSRMLS_* macros. The fact that these were removed does not imply that ZTS is no longer supported (but I have no idea whether or not the extension does support ZTS).

**Comment by tomassrnka** [comment]
Tested on official php7.3-zts docker image, builds fine, all tests are passing. 

```Number of tests :   76                70
Tests skipped   :    6 (  7.9%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   70 ( 92.1%) (100.0%)
```

**Comment by thesource93** [comment]
when not starting sessions in separate threads you should be fine.
