### ISSUE TITLE
PHP 7 support ready?

### ISSUE THREAD

**Issue by DanielDent** [websupport-sk/pecl-memcache#3]
How ready is this for production use? It appears to compile. If it is somewhat stable, which branches do you recommend? Non blocking IO seems nice, but I'm unclear whether that branch is experimental work or completed work.

Thanks for your work on this module.

**Comment by szabolcsbalogh** [comment]
i used branch naming, that is on pecl.php.net.

master (on pecl.php.net) is memcache v 2.2.7 rewritten for php7 in my php7 branch. Tests should pass on linux, windows i didn't tested.

NON_BLOCKING_IO (on pecl.php.net) branch is v 3.0.9-dev rewritten for php7 in my NON_BLOCKING_IO_php7 branch.

See http://marc.info/?l=pecl-dev&m=144906217213648&w=2. If you avoid udp connection to memcache, i think it should be stable. I'm using it in production, and i didn't have any problems with it yet.

Also you an see issue #2, and ask them if this works for him.

**Comment by DanielDent** [comment]
Thanks!
