### ISSUE TITLE
php7.3 error

### ISSUE THREAD

**Issue by 1265578519** [websupport-sk/pecl-memcache#31]
php7.3 error

**Comment by 1265578519** [comment]
[root@new_centos6 ~]# unzip -o php-memcache-3.0.9-dev.zip
Archive:  php-memcache-3.0.9-dev.zip
e702b5f91ec222e20d1d5cea0ffc6be012992d70
   creating: php-memcache-3.0.9-dev/
  inflating: php-memcache-3.0.9-dev/.gitignore  
 extracting: php-memcache-3.0.9-dev/CREDITS  
  inflating: php-memcache-3.0.9-dev/LICENSE  
  inflating: php-memcache-3.0.9-dev/README  
  inflating: php-memcache-3.0.9-dev/config.m4  
  inflating: php-memcache-3.0.9-dev/config.w32  
  inflating: php-memcache-3.0.9-dev/config9.m4  
  inflating: php-memcache-3.0.9-dev/example.php  
  inflating: php-memcache-3.0.9-dev/memcache.php  
  inflating: php-memcache-3.0.9-dev/package.xml  
   creating: php-memcache-3.0.9-dev/php5/
  inflating: php-memcache-3.0.9-dev/php5/memcache.c  
  inflating: php-memcache-3.0.9-dev/php5/memcache_ascii_protocol.c  
  inflating: php-memcache-3.0.9-dev/php5/memcache_binary_protocol.c  
  inflating: php-memcache-3.0.9-dev/php5/memcache_consistent_hash.c  
  inflating: php-memcache-3.0.9-dev/php5/memcache_pool.c  
  inflating: php-memcache-3.0.9-dev/php5/memcache_pool.h  
  inflating: php-memcache-3.0.9-dev/php5/memcache_queue.c  
  inflating: php-memcache-3.0.9-dev/php5/memcache_queue.h  
  inflating: php-memcache-3.0.9-dev/php5/memcache_session.c  
  inflating: php-memcache-3.0.9-dev/php5/memcache_standard_hash.c  
  inflating: php-memcache-3.0.9-dev/php5/php_memcache.h  
   creating: php-memcache-3.0.9-dev/php7/
  inflating: php-memcache-3.0.9-dev/php7/memcache.c  
  inflating: php-memcache-3.0.9-dev/php7/memcache_ascii_protocol.c  
  inflating: php-memcache-3.0.9-dev/php7/memcache_binary_protocol.c  
  inflating: php-memcache-3.0.9-dev/php7/memcache_consistent_hash.c  
  inflating: php-memcache-3.0.9-dev/php7/memcache_pool.c  
  inflating: php-memcache-3.0.9-dev/php7/memcache_pool.h  
  inflating: php-memcache-3.0.9-dev/php7/memcache_queue.c  
  inflating: php-memcache-3.0.9-dev/php7/memcache_queue.h  
  inflating: php-memcache-3.0.9-dev/php7/memcache_session.c  
  inflating: php-memcache-3.0.9-dev/php7/memcache_standard_hash.c  
  inflating: php-memcache-3.0.9-dev/php7/php_memcache.h  
  inflating: php-memcache-3.0.9-dev/profile.php  
   creating: php-memcache-3.0.9-dev/tests/
  inflating: php-memcache-3.0.9-dev/tests/001.phpt  
  inflating: php-memcache-3.0.9-dev/tests/002.phpt  
  inflating: php-memcache-3.0.9-dev/tests/003.phpt  
  inflating: php-memcache-3.0.9-dev/tests/004.phpt  
  inflating: php-memcache-3.0.9-dev/tests/005.phpt  
  inflating: php-memcache-3.0.9-dev/tests/006.phpt  
  inflating: php-memcache-3.0.9-dev/tests/007.phpt  
  inflating: php-memcache-3.0.9-dev/tests/008.phpt  
  inflating: php-memcache-3.0.9-dev/tests/009.phpt  
  inflating: php-memcache-3.0.9-dev/tests/010.phpt  
  inflating: php-memcache-3.0.9-dev/tests/011.phpt  
  inflating: php-memcache-3.0.9-dev/tests/012.phpt  
  inflating: php-memcache-3.0.9-dev/tests/013.phpt  
  inflating: php-memcache-3.0.9-dev/tests/014.phpt  
  inflating: php-memcache-3.0.9-dev/tests/015.phpt  
  inflating: php-memcache-3.0.9-dev/tests/016.phpt  
  inflating: php-memcache-3.0.9-dev/tests/017.phpt  
  inflating: php-memcache-3.0.9-dev/tests/018.phpt  
  inflating: php-memcache-3.0.9-dev/tests/019.phpt  
  inflating: php-memcache-3.0.9-dev/tests/019a.phpt  
  inflating: php-memcache-3.0.9-dev/tests/020.phpt  
  inflating: php-memcache-3.0.9-dev/tests/021.phpt  
  inflating: php-memcache-3.0.9-dev/tests/022.phpt  
  inflating: php-memcache-3.0.9-dev/tests/022a.phpt  
  inflating: php-memcache-3.0.9-dev/tests/023.phpt  
  inflating: php-memcache-3.0.9-dev/tests/024.phpt  
  inflating: php-memcache-3.0.9-dev/tests/024a.phpt  
  inflating: php-memcache-3.0.9-dev/tests/025.phpt  
  inflating: php-memcache-3.0.9-dev/tests/026.phpt  
  inflating: php-memcache-3.0.9-dev/tests/027.phpt  
  inflating: php-memcache-3.0.9-dev/tests/027a.phpt  
  inflating: php-memcache-3.0.9-dev/tests/028.phpt  
  inflating: php-memcache-3.0.9-dev/tests/029.phpt  
  inflating: php-memcache-3.0.9-dev/tests/030.phpt  
  inflating: php-memcache-3.0.9-dev/tests/031.phpt  
  inflating: php-memcache-3.0.9-dev/tests/032.phpt  
  inflating: php-memcache-3.0.9-dev/tests/033.phpt  
  inflating: php-memcache-3.0.9-dev/tests/034.phpt  
  inflating: php-memcache-3.0.9-dev/tests/035.phpt  
  inflating: php-memcache-3.0.9-dev/tests/036.phpt  
  inflating: php-memcache-3.0.9-dev/tests/037.phpt  
  inflating: php-memcache-3.0.9-dev/tests/038.phpt  
  inflating: php-memcache-3.0.9-dev/tests/039.phpt  
  inflating: php-memcache-3.0.9-dev/tests/040.phpt  
  inflating: php-memcache-3.0.9-dev/tests/041.phpt  
  inflating: php-memcache-3.0.9-dev/tests/042.phpt  
  inflating: php-memcache-3.0.9-dev/tests/043.phpt  
  inflating: php-memcache-3.0.9-dev/tests/044.phpt  
  inflating: php-memcache-3.0.9-dev/tests/045.phpt  
  inflating: php-memcache-3.0.9-dev/tests/046.phpt  
  inflating: php-memcache-3.0.9-dev/tests/047.phpt  
  inflating: php-memcache-3.0.9-dev/tests/047a.phpt  
  inflating: php-memcache-3.0.9-dev/tests/048.phpt  
  inflating: php-memcache-3.0.9-dev/tests/049.phpt  
  inflating: php-memcache-3.0.9-dev/tests/050.phpt  
  inflating: php-memcache-3.0.9-dev/tests/051.phpt  
  inflating: php-memcache-3.0.9-dev/tests/052.phpt  
  inflating: php-memcache-3.0.9-dev/tests/053.phpt  
  inflating: php-memcache-3.0.9-dev/tests/054.phpt  
  inflating: php-memcache-3.0.9-dev/tests/055.phpt  
  inflating: php-memcache-3.0.9-dev/tests/056.phpt  
  inflating: php-memcache-3.0.9-dev/tests/057.phpt  
  inflating: php-memcache-3.0.9-dev/tests/058.phpt  
  inflating: php-memcache-3.0.9-dev/tests/100.phpt  
  inflating: php-memcache-3.0.9-dev/tests/100a.phpt  
  inflating: php-memcache-3.0.9-dev/tests/100b.phpt  
  inflating: php-memcache-3.0.9-dev/tests/bug73539.phpt  
  inflating: php-memcache-3.0.9-dev/tests/connect.inc  
  inflating: php-memcache-3.0.9-dev/tests/memcache.sh  
  inflating: php-memcache-3.0.9-dev/tests/pecl11221.phpt  
  inflating: php-memcache-3.0.9-dev/tests/pecl16442.phpt  
  inflating: php-memcache-3.0.9-dev/tests/pecl16536.phpt  
  inflating: php-memcache-3.0.9-dev/tests/pecl17518.phpt  
  inflating: php-memcache-3.0.9-dev/tests/pecl17566.phpt  
  inflating: php-memcache-3.0.9-dev/tests/pecl63142.phpt  
  inflating: php-memcache-3.0.9-dev/tests/pecl63272.phpt  
[root@new_centos6 ~]# cd php-memcache-3.0.9-dev
[root@new_centos6 php-memcache-3.0.9-dev]# /vhs/kangle/ext/tpl_php730/bin/phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
[root@new_centos6 php-memcache-3.0.9-dev]# ./configure --with-php-config=/vhs/kangle/ext/tpl_php730/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /vhs/kangle/ext/tpl_php730
checking for PHP includes... -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib
checking for PHP extension directory... /vhs/kangle/ext/tpl_php730/lib/php/extensions/no-debug-non-zts-20180731
checking for PHP installed headers prefix... /vhs/kangle/ext/tpl_php730/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable memcache support... yes, shared
checking whether to enable memcache session handler support... yes
checking for the location of ZLIB... no
checking for the location of zlib... /usr
checking PHP version... PHP 7.x
checking for session includes... /vhs/kangle/ext/tpl_php730/include/php
checking for memcache session support... enabled
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1966080
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
[root@new_centos6 php-memcache-3.0.9-dev]# make -j 4
/bin/sh /root/php-memcache-3.0.9-dev/libtool --mode=compile cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php-memcache-3.0.9-dev/php7/memcache.c -o php7/memcache.lo 
/bin/sh /root/php-memcache-3.0.9-dev/libtool --mode=compile cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php-memcache-3.0.9-dev/php7/memcache_pool.c -o php7/memcache_pool.lo 
/bin/sh /root/php-memcache-3.0.9-dev/libtool --mode=compile cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php-memcache-3.0.9-dev/php7/memcache_queue.c -o php7/memcache_queue.lo 
/bin/sh /root/php-memcache-3.0.9-dev/libtool --mode=compile cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php-memcache-3.0.9-dev/php7/memcache_ascii_protocol.c -o php7/memcache_ascii_protocol.lo 
mkdir php7/.libs
mkdir php7/.libs
mkdir: cannot create directory `php7/.libs': File exists
 cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php-memcache-3.0.9-dev/php7/memcache.c  -fPIC -DPIC -o php7/.libs/memcache.o
 cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php-memcache-3.0.9-dev/php7/memcache_queue.c  -fPIC -DPIC -o php7/.libs/memcache_queue.o
 cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php-memcache-3.0.9-dev/php7/memcache_ascii_protocol.c  -fPIC -DPIC -o php7/.libs/memcache_ascii_protocol.o
 cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php-memcache-3.0.9-dev/php7/memcache_pool.c  -fPIC -DPIC -o php7/.libs/memcache_pool.o
/root/php-memcache-3.0.9-dev/php7/memcache.c: 在函数‘mmc_find_persistent’中:
/root/php-memcache-3.0.9-dev/php7/memcache.c:731: 错误：赋值运算的左操作数必须是左值
/root/php-memcache-3.0.9-dev/php7/memcache.c: 在函数‘php_mmc_pool_addserver’中:
/root/php-memcache-3.0.9-dev/php7/memcache.c:789: 错误：自增操作数必须是左值
/root/php-memcache-3.0.9-dev/php7/memcache.c: 在函数‘php_mmc_connect’中:
/root/php-memcache-3.0.9-dev/php7/memcache.c:873: 错误：自增操作数必须是左值
make: *** [php7/memcache.lo] 错误 1
make: *** 正在等待未完成的任务....
[root@new_centos6 php-memcache-3.0.9-dev]# make install
/bin/sh /root/php-memcache-3.0.9-dev/libtool --mode=compile cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php-memcache-3.0.9-dev/php7/memcache.c -o php7/memcache.lo 
 cc -I/vhs/kangle/ext/tpl_php730/include/php -I. -I/root/php-memcache-3.0.9-dev -DPHP_ATOM_INC -I/root/php-memcache-3.0.9-dev/include -I/root/php-memcache-3.0.9-dev/main -I/root/php-memcache-3.0.9-dev -I/vhs/kangle/ext/tpl_php730/include/php -I/vhs/kangle/ext/tpl_php730/include/php/main -I/vhs/kangle/ext/tpl_php730/include/php/TSRM -I/vhs/kangle/ext/tpl_php730/include/php/Zend -I/vhs/kangle/ext/tpl_php730/include/php/ext -I/vhs/kangle/ext/tpl_php730/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php-memcache-3.0.9-dev/php7/memcache.c  -fPIC -DPIC -o php7/.libs/memcache.o
/root/php-memcache-3.0.9-dev/php7/memcache.c: 在函数‘mmc_find_persistent’中:
/root/php-memcache-3.0.9-dev/php7/memcache.c:731: 错误：赋值运算的左操作数必须是左值
/root/php-memcache-3.0.9-dev/php7/memcache.c: 在函数‘php_mmc_pool_addserver’中:
/root/php-memcache-3.0.9-dev/php7/memcache.c:789: 错误：自增操作数必须是左值
/root/php-memcache-3.0.9-dev/php7/memcache.c: 在函数‘php_mmc_connect’中:
/root/php-memcache-3.0.9-dev/php7/memcache.c:873: 错误：自增操作数必须是左值
make: *** [php7/memcache.lo] 错误 1
[root@new_centos6 php-memcache-3.0.9-dev]#

**Comment by nikolamakin** [comment]
楼主你解决了吗？解决了反馈一下！

**Comment by 1265578519** [comment]
@nikolamakin 没有解决

**Comment by tomassrnka** [comment]
Should be fixed in 4.0.0. Please test it.

**Comment by tomassrnka** [comment]
All tests passing closing.
