### ISSUE TITLE
php7.3 error

### ISSUE THREAD

**Issue by nikolamakin** [websupport-sk/pecl-memcache#32]
[root@localhost pecl-memcache-php7]# /server/php7/bin/phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
[root@localhost pecl-memcache-php7]# ./configure --with-php-config=/server/php7/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /server/php7
checking for PHP includes... -I/server/php7/include/php -I/server/php7/include/php/main -I/server/php7/include/php/TSRM -I/server/php7/include/php/Zend -I/server/php7/include/php/ext -I/server/php7/include/php/ext/date/lib
checking for PHP extension directory... /server/php7/lib/php/extensions/no-debug-zts-20180731
checking for PHP installed headers prefix... /server/php7/include/php
checking if debug is enabled... no
checking if zts is enabled... yes
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable memcache support... yes, shared
checking whether to enable memcache session handler support... yes
checking for the location of ZLIB... no
checking for the location of zlib... /usr
checking for session includes... /server/php7/include/php
checking for memcache session support... enabled
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
[root@localhost pecl-memcache-php7]# make
/bin/sh /home/pecl-memcache-php7/libtool --mode=compile cc -I/server/php7/include/php -I. -I/home/pecl-memcache-php7 -DPHP_ATOM_INC -I/home/pecl-memcache-php7/include -I/home/pecl-memcache-php7/main -I/home/pecl-memcache-php7 -I/server/php7/include/php -I/server/php7/include/php/main -I/server/php7/include/php/TSRM -I/server/php7/include/php/Zend -I/server/php7/include/php/ext -I/server/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/pecl-memcache-php7/memcache.c -o memcache.lo 
mkdir .libs
 cc -I/server/php7/include/php -I. -I/home/pecl-memcache-php7 -DPHP_ATOM_INC -I/home/pecl-memcache-php7/include -I/home/pecl-memcache-php7/main -I/home/pecl-memcache-php7 -I/server/php7/include/php -I/server/php7/include/php/main -I/server/php7/include/php/TSRM -I/server/php7/include/php/Zend -I/server/php7/include/php/ext -I/server/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/pecl-memcache-php7/memcache.c  -fPIC -DPIC -o .libs/memcache.o
/home/pecl-memcache-php7/memcache.c: In function ‘php_mmc_store’:
/home/pecl-memcache-php7/memcache.c:1842:3: warning: passing argument 1 of ‘smart_string_free_ex’ from incompatible pointer type [enabled by default]
   smart_string_free(&buf);
   ^
In file included from /server/php7/include/php/ext/standard/php_smart_string.h:21:0,
                 from /home/pecl-memcache-php7/memcache.c:42:
/server/php7/include/php/Zend/zend_smart_string.h:67:32: note: expected ‘struct smart_string *’ but argument is of type ‘struct smart_str *’
 static zend_always_inline void smart_string_free_ex(smart_string *str, zend_bool persistent) {
                                ^
/home/pecl-memcache-php7/memcache.c: In function ‘php_mmc_connect’:
/home/pecl-memcache-php7/memcache.c:1946:24: error: lvalue required as increment operand
   GC_REFCOUNT(list_res)++;
                        ^
/home/pecl-memcache-php7/memcache.c:1965:24: error: lvalue required as increment operand
   GC_REFCOUNT(list_res)++;
                        ^
/home/pecl-memcache-php7/memcache.c: In function ‘zif_memcache_add_server’:
/home/pecl-memcache-php7/memcache.c:2057:24: error: lvalue required as increment operand
   GC_REFCOUNT(list_res)++;
                        ^
/home/pecl-memcache-php7/memcache.c: In function ‘mmc_find_persistent’:
/home/pecl-memcache-php7/memcache.c:2203:19: error: lvalue required as left operand of assignment
   GC_REFCOUNT(le) = 1;
                   ^
/home/pecl-memcache-php7/memcache.c:2220:19: error: lvalue required as left operand of assignment
   GC_REFCOUNT(le) = 1;
                   ^
make: *** [memcache.lo] Error 1

**Comment by Joungkyun** [comment]
use follow patch and attache patch file with zip archive

```diff
diff -ruNp memcache.org/memcache.c memcache/memcache.c
--- memcache.org/memcache.c	2017-02-24 21:03:57.000000000 +0900
+++ memcache/memcache.c	2019-01-12 01:32:55.317420944 +0900
@@ -1943,7 +1943,11 @@ static void php_mmc_connect (INTERNAL_FU
 		object_init_ex(return_value, memcache_class_entry_ptr);
 		list_res = zend_register_resource(pool, le_memcache_pool);
 		add_property_resource(return_value, "connection", list_res);
+#if PHP_VERSION_ID < 70300
 		GC_REFCOUNT(list_res)++;
+#else
+		GC_ADDREF(list_res);
+#endif
 	}
 	else if ((zv=zend_hash_str_find(Z_OBJPROP_P(mmc_object), "connection", sizeof("connection")-1)) != NULL) {
 		pool = zend_fetch_resource_ex(zv, "connection", le_memcache_pool);
@@ -1962,7 +1966,11 @@ static void php_mmc_connect (INTERNAL_FU
 
 		list_res = zend_register_resource(pool, le_memcache_pool);
 		add_property_resource(mmc_object, "connection", list_res);
+#if PHP_VERSION_ID < 70300
 		GC_REFCOUNT(list_res)++;
+#else
+		GC_ADDREF(list_res);
+#endif
 
 		RETURN_TRUE;
 	}
@@ -2054,7 +2062,11 @@ PHP_FUNCTION(memcache_add_server)
 		pool = mmc_pool_new();
 		list_res = zend_register_resource(pool, le_memcache_pool);
 		add_property_resource(mmc_object, "connection", list_res);
+#if PHP_VERSION_ID < 70300
 		GC_REFCOUNT(list_res)++;
+#else
+		GC_ADDREF(list_res);
+#endif
 	}
 	else {
 		pool = zend_fetch_resource_ex(connection, "connection", le_memcache_pool);
@@ -2200,7 +2212,11 @@ mmc_t *mmc_find_persistent(zend_string *
 		mmc = mmc_server_new(host, port, 1, timeout, retry_interval);
 		le = zend_register_resource(mmc, le_pmemcache);
 
+#if PHP_VERSION_ID < 70300
 		GC_REFCOUNT(le) = 1;
+#else
+		GC_SET_REFCOUNT(le,1);
+#endif
 
 		/* register new persistent connection */
 		if (zend_hash_str_update_mem(&EG(persistent_list), hash_key, hash_key_len, le, sizeof(*le)) == NULL) {
@@ -2217,7 +2233,11 @@ mmc_t *mmc_find_persistent(zend_string *
 		mmc = mmc_server_new(host, port, 1, timeout, retry_interval);
 		le->type = le_pmemcache;
 		le->ptr  = mmc;
+#if PHP_VERSION_ID < 70300
 		GC_REFCOUNT(le) = 1;
+#else
+		GC_SET_REFCOUNT(le,1);
+#endif
 
 		/* register new persistent connection */
 		if (zend_hash_str_update_mem(&EG(persistent_list), hash_key, hash_key_len, le, sizeof(*le)) == NULL) {
```

[memcache-2.2.7-annyung-php73.patch.zip](https://github.com/websupport-sk/pecl-memcache/files/2750414/memcache-2.2.7-annyung-php73.patch.zip)

**Comment by tomassrnka** [comment]
Current build works fine, all tests are passing on PHP 7.3
