### ISSUE TITLE
Php 7.2.15 issue compile

### ISSUE THREAD

**Issue by micron10** [websupport-sk/pecl-memcache#37]
/php-7.2.15/ext/memcache/php7/memcache.c:643:8: error: too many arguments to function 'mmc_prepare_key_ex'
    if (mmc_prepare_key_ex(ZSTR_VAL(key), ZSTR_LEN(key), request->key, &(request->key_len), MEMCACHE_G(key_prefix)) != MMC_OK) {
        ^~~~~~~~~~~~~~~~~~
In file included from /php-7.2.15/ext/memcache/php7/php_memcache.h:34,
                 from /php-7.2.15/ext/memcache/php7/memcache.c:30:
/php-7.2.15/ext/memcache/php7/memcache_pool.h:399:5: note: declared here
 int mmc_prepare_key_ex(const char *, unsigned int, char *, unsigned int *);
     ^~~~~~~~~~~~~~~~~~

**Comment by borodiychuk** [comment]
This is fixed in PR #39
