### ISSUE TITLE
merge/replace?

### ISSUE THREAD

**Issue by pierrejoye** [websupport-sk/pecl-memcache#4]
Hi,

Great work on the port to 7! Thanks :)

Are you interested to merge into the official (but lacking love, blame me) extension?

I would also like to move the repository to the friendsofphp organization to ease additions of more contributors as well as making it more visible.

Let me know if it sounds good, it would be then easier to move this repository to the organization instead of merging or syncing :)

**Comment by willfitch** [comment]
I agree @pierrejoye.  I'm in the middle of updating the original Memcached extension, and I'd like an extension that is maintained by a community as well.  There are a lot of failed tests and compilation warnings, but the PHP7 API port compiles.

There doesn't seem to be any commits since Nov 2015.  @szabolcsbalogh - can you confirm @pierrejoye's question?

**Comment by szabolcsbalogh** [comment]
hi

i tried again to contact pecl team, but without answer, so...

we can move the repo, and after i make a readme here, that it was moved (because of projects linked it, like https://github.com/LeaseWeb/LswMemcacheBundle/issues/53#issuecomment-168659036)

**Comment by willfitch** [comment]
@szabolcsbalogh - should be able to just make a PR from https://github.com/php/pecl-caching-memcache.

Is that right, @pierrejoye?

**Comment by szabolcsbalogh** [comment]
https://github.com/php/pecl-caching-memcache/pull/4

**Comment by pierrejoye** [comment]
@willfitch  I prefer to actually move it to friendsofphp and really use github. The PHP org is only a mirror of git.php.net and PRs have to be manually merged along other little annoyances.

@szabolcsbalogh If you could add me as admin for this repo, I can then simply move it to friendsofphp/memcache, quick and without losing anything. And we can continue to maintain it there, using github issues trackers, PRs and co.

What do you think?

**Comment by pierrejoye** [comment]
Also github will redirect it as far as I remember, or we can create a new repo with only the README afterwards.

**Comment by szabolcsbalogh** [comment]
@pierrejoye you have been added as admin

**Comment by pierrejoye** [comment]
@szabolcsbalogh  Thanks!

How would you like  to proceed and when? :)

**Comment by szabolcsbalogh** [comment]
you can move it to friendsofphp/memcache as you wrote. Please left me at least collaborator access level after the move. You can move it any time.

**Comment by carlwgeorge** [comment]
Is the move to [friendsofphp/memcache](https://github.com/friendsofphp/memcache) going to happen at some point?  I would like to subscribe to it.

**Comment by szabolcsbalogh** [comment]
@pierrejoye do you have any info about move?

**Comment by Gasol** [comment]
@pierrejoye Could you please move to [friendsofphp/memcache](https://github.com/friendsofphp/memcache) and update link in pecl/memcache site.

**Comment by Jan-E** [comment]
There does not seem any progress on this. Can we fix the PHP 7.1 builds on Windows in the mean time? See https://github.com/websupport-sk/pecl-memcache/pull/15

**Comment by mtibben** [comment]
Hi, I'd love to see a versioned release of this repo, as this has become the de-facto fork many downstream packagers are using
- [Ubuntu](https://launchpad.net/ubuntu/+source/php-memcache) as `3.0.9~20160311.4991c2f-5`.
- [Fedora](https://apps.fedoraproject.org/packages/php-pecl-memcache/) as `3.0.9-0.3.20160311git4991c2f.fc26`
- Brew - https://github.com/Homebrew/homebrew-php/pull/3860 https://github.com/Homebrew/homebrew-php/pull/4025

I'd suggest
- Move the `NON_BLOCKING_IO_php7` branch to master at https://github.com/friendsofphp/memcache
- Tag and release `v4.0.0` at `4991c2f` to dis-ambiguate from the abandoned `v3.x.x` on pecl, to officially tag the "stable" point where these distributions have chosen anyway
- Tag and release master (the old NON_BLOCKING_IO_php7) at `v4.1.0`
- Use [semver](http://semver.org/) and [keepachangelog](http://keepachangelog.com/) for future releases

Thoughts? @websupport-sk @tomassrnka @szabolcsbalogh

**Comment by tomassrnka** [comment]
@mtibben hi, I'm 100% up for it! How can we move it? I've already suggested to move it some time ago.  Any ideas please?

**Comment by glensc** [comment]
looks like ping to @pierrejoye needed

**Comment by tomassrnka** [comment]
Hi, I'm closing this one as a duplicate to #42
