### ISSUE TITLE
php7.3 + WHM error

### ISSUE THREAD

**Issue by HaykSahakyan** [websupport-sk/pecl-memcache#41]
Trying to install on WHM controled server.

/opt/cpanel/ea-php73/root/usr/bin/phpize && ./configure --enable-memcache --with-php-config=/opt/cpanel/ea-php73/root/usr/bin/php-config && make;
_____________________________________________________________
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /opt/cpanel/ea-php73/root/usr
checking for PHP includes... -I/opt/cpanel/ea-php73/root/usr/include/php -I/opt/cpanel/ea-php73/root/usr/include/php/main -I/opt/cpanel/ea-php73/root/usr/include/php/TSRM -I/opt/cpanel/ea-php73/root/usr/include/php/Zend -I/opt/cpanel/ea-php73/root/usr/include/php/ext -I/opt/cpanel/ea-php73/root/usr/include/php/ext/date/lib
checking for PHP extension directory... /opt/cpanel/ea-php73/root/usr/lib64/php/modules
checking for PHP installed headers prefix... /opt/cpanel/ea-php73/root/usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable memcache support... yes, shared
checking whether to enable memcache session handler support... yes
checking for the location of ZLIB... no
checking for the location of zlib... /usr
checking PHP version... PHP 7.x
checking for session includes... /opt/cpanel/ea-php73/root/usr/include/php
checking for memcache session support... enabled
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
/bin/sh /usr/local/src/pecl-memcache-4.0.1-php73/libtool --mode=compile cc -I/opt/cpanel/ea-php73/root/usr/include/php -I. -I/usr/local/src/pecl-memcache-4.0.1-php73 -DPHP_ATOM_INC -I/usr/local/src/pecl-memcache-4.0.1-php73/include -I/usr/local/src/pecl-memcache-4.0.1-php73/main -I/usr/local/src/pecl-memcache-4.0.1-php73 -I/opt/cpanel/ea-php73/root/usr/include/php -I/opt/cpanel/ea-php73/root/usr/include/php/main -I/opt/cpanel/ea-php73/root/usr/include/php/TSRM -I/opt/cpanel/ea-php73/root/usr/include/php/Zend -I/opt/cpanel/ea-php73/root/usr/include/php/ext -I/opt/cpanel/ea-php73/root/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/pecl-memcache-4.0.1-php73/php7/memcache.c -o php7/memcache.lo 
libtool: compile:  cc -I/opt/cpanel/ea-php73/root/usr/include/php -I. -I/usr/local/src/pecl-memcache-4.0.1-php73 -DPHP_ATOM_INC -I/usr/local/src/pecl-memcache-4.0.1-php73/include -I/usr/local/src/pecl-memcache-4.0.1-php73/main -I/usr/local/src/pecl-memcache-4.0.1-php73 -I/opt/cpanel/ea-php73/root/usr/include/php -I/opt/cpanel/ea-php73/root/usr/include/php/main -I/opt/cpanel/ea-php73/root/usr/include/php/TSRM -I/opt/cpanel/ea-php73/root/usr/include/php/Zend -I/opt/cpanel/ea-php73/root/usr/include/php/ext -I/opt/cpanel/ea-php73/root/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/pecl-memcache-4.0.1-php73/php7/memcache.c  -fPIC -DPIC -o php7/.libs/memcache.o
/usr/local/src/pecl-memcache-4.0.1-php73/php7/memcache.c: In function 'php_mmc_store':
/usr/local/src/pecl-memcache-4.0.1-php73/php7/memcache.c:643:4: error: too many arguments to function 'mmc_prepare_key_ex'
    if (mmc_prepare_key_ex(ZSTR_VAL(key), ZSTR_LEN(key), request->key, &(request->key_len), MEMCACHE_G(key_prefix)) != MMC_OK) {
    ^
In file included from /usr/local/src/pecl-memcache-4.0.1-php73/php7/php_memcache.h:34:0,
                 from /usr/local/src/pecl-memcache-4.0.1-php73/php7/memcache.c:30:
/usr/local/src/pecl-memcache-4.0.1-php73/php7/memcache_pool.h:399:5: note: declared here
 int mmc_prepare_key_ex(const char *, unsigned int, char *, unsigned int *);
     ^
make: *** [php7/memcache.lo] Error 1

**Comment by tomassrnka** [comment]
Is there any official docker image or source code of your php that we could test on?

**Comment by WaferJay** [comment]
#39

**Comment by tomassrnka** [comment]
This should be fixed already by merging #39  If you still encounter this bug, please reopen / open new issue.
