### ISSUE TITLE
PHP 7.4.0-alpha1: 1 failed test -  040.phpt

### ISSUE THREAD

**Issue by tomassrnka** [websupport-sk/pecl-memcache#52]
PHP_VERSION : 7.4.0alpha1

`TEST 45/77 [tests/040.phpt]`
`========DIFF========`
`003+   int(3)`
`004+   ["key1_abc"]=>`
`004-   ["%s"]=>`
`005-   int(3)`
`011+   int(2)`
`012+   ["key1_abc"]=>`
`014+ }`
`015+ array(2) {`
`017+   int(3)`
`018+   ["key1_abc"]=>`
`019-   int(3)`
`021- array(2) {`
`022-   ["%s"]=>`
`023-   int(1)`
`024-   ["%s"]=>`
`025-   int(2)`
`026- }`
`025+   int(1)`
`========DONE========`

**Comment by jmalinens** [comment]
@tomassrnka thank You for Your work! I hope to use the extension when PHP7.4 will be stable

**Comment by tomassrnka** [comment]
Works fine now.
