### ISSUE TITLE
when i make，this problem has occurred.

### ISSUE THREAD

**Issue by XyBob** [websupport-sk/pecl-memcache#55]
root/php-7.0.5/ext/memcached/php_memcached_session.c: In function 's_configure_from_ini_values':
/root/php-7.0.5/ext/memcached/php_memcached_session.c:221:22: error: 'MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS' undeclared (first use in this function)
   check_set_behavior(MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS, 1);
                      ^
/root/php-7.0.5/ext/memcached/php_memcached_session.c:195:42: note: in definition of macro 'check_set_behavior'
  if ((rc = memcached_behavior_set(memc, (behavior), (value))) != MEMCACHED_SUCCESS) { \
                                          ^
/root/php-7.0.5/ext/memcached/php_memcached_session.c:221:22: note: each undeclared identifier is reported only once for each function it appears in
   check_set_behavior(MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS, 1);
                      ^
/root/php-7.0.5/ext/memcached/php_memcached_session.c:195:42: note: in definition of macro 'check_set_behavior'
  if ((rc = memcached_behavior_set(memc, (behavior), (value))) != MEMCACHED_SUCCESS) { \
                                          ^
/root/php-7.0.5/ext/memcached/php_memcached_session.c:229:32: error: 'MEMCACHED_CALLBACK_NAMESPACE' undeclared (first use in this function)
   memcached_callback_set(memc, MEMCACHED_CALLBACK_NAMESPACE, MEMC_SESS_STR_INI(prefix));
                                ^
make: *** [php_memcached_session.lo] Error 1

how to solve this problem

**Comment by XyBob** [comment]
my php version is  PHP 7.0.32-4+ubuntu14.04.1+deb.sury.org+1

**Comment by tomassrnka** [comment]
The source code probably belongs to php memcache*d* not to php-memcache extension. 

This extension builds and runs fine with PHP 7.0. Tested again with PHP 7.0.33 from official docker image. 

```=====================================================================
PHP         : /usr/local/bin/php
PHP_SAPI    : cli
PHP_VERSION : 7.0.33
ZEND_VERSION: 3.0.0
PHP_OS      : Linux - Linux 2e2041df0008 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
INI actual  : /usr/src/pecl-memcache/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
PHP         : /usr/local/bin/phpdbg
PHP_SAPI    : phpdbg
PHP_VERSION : 7.0.33
ZEND_VERSION: 3.0.0
PHP_OS      : Linux - Linux 2e2041df0008 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
INI actual  : /usr/src/pecl-memcache/tmp-php.ini
More .INIs  
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   33
---------------------------------------------------------------------

Number of tests :   77                72
Tests skipped   :    5 (  6.5%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   72 ( 93.5%) (100.0%)
---------------------------------------------------------------------
Time taken      :    7 seconds
=====================================================================```
