### ISSUE TITLE
Please follow semver and keep GitHub tags and PECL in sync

### ISSUE THREAD

**Issue by dzuelke** [websupport-sk/pecl-memcache#61]
Thanks for picking up work again on this extension! Looking forward to people using it again and eventually making it available for users on Heroku :)

In the interest of transparency and trust in the project, I'd like to ask for the following process changes:

- do not publish to PECL without a corresponding GitHub tag - this is important for trust (I can't see the source for that latest 4.0.5.2 tag on GitHub and easily verify what changed)
- use strict semantic versioning for this project, meaning
  - no fourth part to the version - the recent 4.0.5.1 release with the version number mismatch in `php_memcache.h` should simply have been 4.0.6
  - 4.0.x for additional fixes
  - 4.1.0 for any additions to the API
  - 5.0.0 for any breakage
- maintain a changelog that lists all changes, including stuff like those trivial version bumps that fixed the headers
- remove the latest version mentions from `README`, it'll otherwise just always be stale

Keep up the good work, and happy holidays!

**Comment by tomassrnka** [comment]
Hi,

thank you for the feedback! I appreciate it! 

This was my first PECL release, I will do my best to keep it in sync & within the rules & keeping the changelog uptodate.

I will fix version numbering tomorrow with new minor release. 

🎄Happy holidays to you as well! 🎄

**Comment by dzuelke** [comment]
Cool stuff. With the first point I meant of course the latest 4.0.5.2 release that was on PECL but without any details in the change log and no GitHub tag. Edited original comment to clarify.

✌🏼
