### ISSUE TITLE
"Memcache session handling, zend_mm_heap corrupted" on bugs.php.net

### ISSUE THREAD

**Issue by TysonAndre** [websupport-sk/pecl-memcache#65]
https://bugs.php.net/bug.php?id=77900

Sorry if you've already seen this. (The issue has no assignee or response comments on bugs.php.net, so I can't tell, and I personally don't check bugs.php.net frequently or know how to subscribe to bug reports for a given extension.)

The bug was for memcache 3.0.9 with php 7.3. I can't reproduce the zend_mm_heap issue in 4.0.5.2 from PECL (trying with NTS on 7.4 only). However, I see a memory leak (same leak 4 times) instead in 4.0.5.2, when running with a PHP 7.4.3-dev NTS DEBUG build.
(The impact is hopefully limited to just a few http requests for sessions, and should get garbage collected after the HTTP response is sent? I haven't investigated further)

```
» php --no-php-ini --php-ini test.ini test.php
array(1) {                                     
  ["test"]=>                                   
  bool(true)                                   
}                                              
[Fri Mar  6 15:40:14 2020]  Script:  '/path/to/test.php'
/tmp/pear/temp/memcache/php7/memcache_queue.c(35) :  Freeing 0x00007f0542e7d700 (208 bytes), script=/path/to/test.php
Last leak repeated 3 times
=== Total 4 memory leaks detected ===
```

**Comment by TysonAndre** [comment]
Should this and some of the other tickets mentioned in the description of https://github.com/websupport-sk/pecl-memcache/pull/76 be closed?

>added support for reflection 64
>added test for 53
>fixed failing tests including 46 and 57
>fixed underlying issue in 7

**Comment by thesource93** [comment]
fixed in https://github.com/websupport-sk/pecl-memcache/pull/76
