### ISSUE TITLE
Session Redundancy with Failover doesn't work on PHP7

### ISSUE THREAD

**Issue by itrack** [websupport-sk/pecl-memcache#85]
Session Redundancy with Failover doesn't work on PHP7, how can replicate the problem:
- Install 2 memcache servers
- Install Memcache version from branch NON_BLOCKING_IO_php7
- Memcache setup:
```
memcache.redundancy = 1
memcache.session_redundancy = 3
memcache.allow_failover = 1
memcache.hash_strategy = consistent
```
- PHP Script:
```
<?php

$memcache1 = "tcp://172.18.0.2:11211?persistent=1&udp_port=0&weight=1&timeout=1&retry_interval=10";
$memcache2 = "tcp://172.18.0.3:11211?persistent=1&udp_port=0&weight=2&timeout=1&retry_interval=10";
session_save_path("$memcache1,$memcache2");
ini_set('session.save_handler', 'memcache');

session_start();

if (!isset($_SESSION['data'])) {
    $_SESSION['data'] = 1;
    die("New session");
}
$_SESSION['data'] = (int)$_SESSION['data']+1;

echo "Old session: {$_SESSION['data']}";
```
- Turn off the first memcache server and run the script, everything is ok. Start it and give some refresh (to pass retry_interval) and the session is lost. It only happens on one of all the started servers, only one of them, randomly, if we repeat the above steps on the other started servers it will not happen.

I also tested this on the NON_BLOCKING_IO branch with PHP 5.6 and the problem does not manifest.

**Comment by arcticlinux** [comment]
I found that I had to set `memcache.session_save_path` instead of session.save_path in my Ubuntu 20.04, PHP 7.4 configuration

**Comment by itrack** [comment]
Hmmm, nice, and with this configuration does what I wrote above work?

**Comment by arcticlinux** [comment]
Probably with:
`ini_set('memcache.session_save_path', "$memcache1,$memcache2");`

**Comment by drealecs** [comment]
The use-case for this needed behavior was to be able to reboot/restart a memcache VM/container/service without reconfiguring the application memcache server pool.
When stopping one of the  memcache service from the configured pool, no session is lost. Seconds later, when bringing that service back up, the session loss occurs.
I believe I managed to have a fix for the issue (#86) and review would be very much appreciated.

**Comment by itrack** [comment]
The issue has been fixed with the last merge, thank you!

**Comment by drealecs** [comment]
Hey, @thesource93, @tomassrnka, how are you planning the releases that include this fix?
Will it be 4.0.6 for PHP 7.* and 8.0.1 for PHP 8.*?
Thanks!

**Comment by drealecs** [comment]
Hey @thesource93, just another ping here related to an official release.
As noted by recent changes to README: https://github.com/websupport-sk/pecl-memcache/commit/ccf702b14b18fce18a1863e115a7b4c964df952e related to 8.0 release working for PHP lower than 8,
8.0.1 version for PHP 7.3, 7.4 and 8.0 release sounds good as well.
I would like to be able to restart a memcache server in production without loosing sessions. Thanks a lot!

BTW, @tomassrnka , your change related to 4.0.5.1 https://github.com/websupport-sk/pecl-memcache/commit/1ae74d7e2ac07c453558dbd204c006e44babfd22 changed by mistake the date from `2019-12-19` to `2020-12-19` when adding the information about 8.0. Maybe it can be fixed to have a correct README.
